// Sort
export const SET_SORT = "SET_SORT";

// PlayList
export const ADD_TRACK = "ADD_TRACK";
export const SAVE_PLAYLIST = "SAVE_PLAYLIST";
export const GET_PLAYLIST = "GET_PLAYLIST";
export const DELETE_TRACK = "DELETE_TRACK";

// Tracks
export const FETCH_TRACKS = "FETCH_TRACKS";
export const FETCH_TRACKS_PENDING = "FETCH_TRACKS_PENDING";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_TRACKS_FAILURE = "FETCH_TRACKS_FAILURE";
export const CLEAR_FETCH_TRACKS = "CLEAR_FETCH_TRACKS";

// Track
export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_PENDING = "FETCH_TRACK_PENDING";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";
export const FETCH_TRACK_FAILURE = "FETCH_TRACK_FAILURE";

// Cover album
export const FETCH_COVER_ALBUM = "FETCH_COVER_ALBUM";
export const FETCH_COVER_ALBUM_PENDING = "FETCH_COVER_ALBUM_PENDING";
export const FETCH_COVER_ALBUM_SUCCESS = "FETCH_COVER_ALBUM_SUCCESS";
export const FETCH_COVER_ALBUM_FAILURE = "FETCH_COVER_ALBUM_FAILURE";

// Lyrics track
export const FETCH_LYRICS_TRACK = "FETCH_LYRICS_TRACK";
export const FETCH_LYRICS_TRACK_PENDING = "FETCH_LYRICS_TRACK_PENDING";
export const FETCH_LYRICS_TRACK_SUCCESS = "FETCH_LYRICS_TRACK_SUCCESS";
export const FETCH_LYRICS_TRACK_FAILURE = "FETCH_LYRICS_TRACK_FAILURE";

// Song page
export const TOGGLE_PAGE = "TOGGLE_PAGE";

